project:
  type: website
  output-dir: docs   # GitHub Pages leerá esta carpeta
  render:
    - "index.qmd"
  resources:
    - "vignettes/Ferrer-Ferrando_etal_Ecography/"
    - "vignettes/Package_Example/"

website:
  page-navigation: true
  title: "EcoForge R package"
  site-url: "https://natureprotectiondff.github.io/Ecoforge-R-package"
  repo-url: https://github.com/NatureProtectionDFF/Ecoforge-R-package
  repo-actions: [edit, issue]
  
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; GPL-3.0 License, EcoForge, 2025"

  sidebar:
    logo: "images/Logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/NatureProtectionDFF/Ecoforge-R-package
        text: "GitHub repository"
      - icon: globe
        href: https://sites.google.com/view/davidferrer/english?authuser=0
        text: "David Ferrer website"
      - icon: journal
        href: https://nsojournals.onlinelibrary.wiley.com/doi/10.1111/ecog.07766?af=R
        text: "Manuscript with example use"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Schedule
      - section: "Functions descriptions"
        contents:
          - href: "reference/abundance2pres.html"
            text: "abundance2pres"
          - href: "reference/countOcc.html"
            text: "countOcc"
          - href: "reference/generateClim.html"
            text: "generateClim"
          - href: "reference/generateMonthlyPrec.html"
            text: "generateMonthlyPrec"
          - href: "reference/generateMonthlyTemp.html"
            text: "generateMonthlyTemp"
          - href: "reference/generatePoints.html"
            text: "generatePoints"
          - href: "reference/generateVar.html"
            text: "generateVar"
          - href: "reference/logistic.html"
            text: "logistic"
          - href: "reference/pointSample.html"
            text: "pointSample"
          - href: "reference/randomSamp.html"
            text: "randomSamp"
          - href: "reference/scale01.html"
            text: "scale01"
          - href: "reference/transectSample.html"
            text: "transectSample"
          - href: "reference/uniformSamp.html"
            text: "uniformSamp"
      - section: Vignettes
        contents:
          - href: vignettes/Ferrer-Ferrando_etal_Ecography/Simulation.vignette.html
            text: "Ferrer-Ferrando et al. Ecography"
          - href: vignettes/Package_Example/QUARTO_ECOFORGE_HTML_PDF.html
            text: "Package Example"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    code-copy: true
    code-overflow: wrap
