---
title: "Ecoforge R package"
author: "David Ferrer Ferrando & Pedro Tarroso"
---

An R package with a set of tools for simulating ecological environments and generate species' counts or presence/absence data for ecological analyses.

## Instalation

``` r
# install.packages("devtools")
install_github("https://github.com/NatureProtectionDFF/Ecoforge-R-package")

library(ecoforge)
ls("package:ecoforge")
```

## Functions descriptions

-   [abundance2pres](reference/abundance2pres.html)
-   [countOcc](reference/countOcc.html)
-   [generateClim](reference/generateClim.html)
-   [generateMonthlyPrec](reference/generateMonthlyPrec.html)
-   [generateMonthlyTemp](reference/generateMonthlyTemp.html)
-   [generatePoints](reference/generatePoints.html)
-   [generateVar](reference/generateVar.html)
-   [logistic](reference/logistic.html)
-   [pointSample](reference/pointSample.html)
-   [randomSamp](reference/randomSamp.html)
-   [scale01](reference/scale01.html)
-   [transectSample](reference/transectSample.html)
-   [uniformSamp](reference/uniformSamp.html)

## Available vignettes

-   [Ferrer-Ferrando et al. Ecography](vignettes/Ferrer-Ferrando_etal_Ecography/Simulation.vignette.html)
-   [Package Example](vignettes/Package_Example/QUARTO_ECOFORGE_HTML_PDF.html)
